package com.bank.bian.leadopportunitymanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Lead Opportunity Management
 *
 * Business Area:      Sales and Service
 * Business Domain:    Sales
 * Functional Pattern: Manage
 * Asset Type:         Sales Lead
 * Control Record:     Sales Lead Management Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Lead Opportunity Management — BIAN Semantic API")
                .description("Service Domain 'Lead Opportunity Management' (Manage pattern) "
                        + "operating on the 'Sales Lead Management Plan' control record.")
                .version("0.1.0"));
    }
}
